version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: airport-db-redis
    ports:
      - "9021:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Optional: Redis Commander for GUI management (development only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: airport-db-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379  # This remains 6379 as it's the internal container port
    depends_on:
      - redis
    profiles:
      - dev

volumes:
  redis-data:
    driver: local