/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AirportsRouteImport } from './routes/airports'
import { Route as R404RouteImport } from './routes/_404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlightsFlightIdRouteImport } from './routes/flights.$flightId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as DemoLocationlistRouteImport } from './routes/demo.locationlist'
import { Route as AirportsIataCodeRouteImport } from './routes/airports.$iataCode'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo.start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo.form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo.form.address'
import { ServerRoute as ApiDemoNamesServerRouteImport } from './routes/api.demo-names'

const rootServerRouteImport = createServerRootRoute()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsRoute = AirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/_404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightIdRoute = FlightsFlightIdRouteImport.update({
  id: '/$flightId',
  path: '/$flightId',
  getParentRoute: () => FlightsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLocationlistRoute = DemoLocationlistRouteImport.update({
  id: '/demo/locationlist',
  path: '/demo/locationlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsIataCodeRoute = AirportsIataCodeRouteImport.update({
  id: '/$iataCode',
  path: '/$iataCode',
  getParentRoute: () => AirportsRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesServerRoute = ApiDemoNamesServerRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airports': typeof AirportsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/flights': typeof FlightsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/airports/$iataCode': typeof AirportsIataCodeRoute
  '/demo/locationlist': typeof DemoLocationlistRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airports': typeof AirportsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/flights': typeof FlightsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/airports/$iataCode': typeof AirportsIataCodeRoute
  '/demo/locationlist': typeof DemoLocationlistRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_404': typeof R404Route
  '/airports': typeof AirportsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/flights': typeof FlightsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/airports/$iataCode': typeof AirportsIataCodeRoute
  '/demo/locationlist': typeof DemoLocationlistRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airports'
    | '/favorites'
    | '/flights'
    | '/settings'
    | '/airports/$iataCode'
    | '/demo/locationlist'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/flights/$flightId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airports'
    | '/favorites'
    | '/flights'
    | '/settings'
    | '/airports/$iataCode'
    | '/demo/locationlist'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/flights/$flightId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/_404'
    | '/airports'
    | '/favorites'
    | '/flights'
    | '/settings'
    | '/airports/$iataCode'
    | '/demo/locationlist'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/flights/$flightId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AirportsRoute: typeof AirportsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  FlightsRoute: typeof FlightsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  DemoLocationlistRoute: typeof DemoLocationlistRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}
export interface FileServerRoutesByFullPath {
  '/api/demo-names': typeof ApiDemoNamesServerRoute
}
export interface FileServerRoutesByTo {
  '/api/demo-names': typeof ApiDemoNamesServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/demo-names': typeof ApiDemoNamesServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/demo-names'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/demo-names'
  id: '__root__' | '/api/demo-names'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiDemoNamesServerRoute: typeof ApiDemoNamesServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_404': {
      id: '/_404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$flightId': {
      id: '/flights/$flightId'
      path: '/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof FlightsFlightIdRouteImport
      parentRoute: typeof FlightsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/locationlist': {
      id: '/demo/locationlist'
      path: '/demo/locationlist'
      fullPath: '/demo/locationlist'
      preLoaderRoute: typeof DemoLocationlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports/$iataCode': {
      id: '/airports/$iataCode'
      path: '/$iataCode'
      fullPath: '/airports/$iataCode'
      preLoaderRoute: typeof AirportsIataCodeRouteImport
      parentRoute: typeof AirportsRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AirportsRouteChildren {
  AirportsIataCodeRoute: typeof AirportsIataCodeRoute
}

const AirportsRouteChildren: AirportsRouteChildren = {
  AirportsIataCodeRoute: AirportsIataCodeRoute,
}

const AirportsRouteWithChildren = AirportsRoute._addFileChildren(
  AirportsRouteChildren,
)

interface FlightsRouteChildren {
  FlightsFlightIdRoute: typeof FlightsFlightIdRoute
}

const FlightsRouteChildren: FlightsRouteChildren = {
  FlightsFlightIdRoute: FlightsFlightIdRoute,
}

const FlightsRouteWithChildren =
  FlightsRoute._addFileChildren(FlightsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AirportsRoute: AirportsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  FlightsRoute: FlightsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  DemoLocationlistRoute: DemoLocationlistRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiDemoNamesServerRoute: ApiDemoNamesServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
